### ISSUE TITLE
more MathML parsing trouble "expression_mathml": "<mi>S0</mi>"

### ISSUE THREAD

**Issue by anandijain** [DARPA-ASKEM/Model-Representations#15]
back in the mira repo, I encountered formatting MathML nodes. can we make sure that these aren't in any mathml that we're parsing?

ref: https://github.com/indralab/mira/issues/159

**Comment by anandijain** [comment]
for now, im just changing them manually for my pr at https://github.com/DARPA-ASKEM/simulation-service/pull/29

**Comment by bgyori** [comment]
I think this is just an artifact of the example model JSON, and I believe the mathml expressions were populated by ChatGPT in this case, we didn't consciously decide to use the `<mi>` tag. I can PR a change to the example that changes `<mi>S0</mi>` to `<ci>S0</ci>` which should parse okay. Does that sound good, @anandijain?

**Comment by anandijain** [comment]
thanks
