### ISSUE TITLE
Inconsistency in properties within the schemas

### ISSUE THREAD

**Issue by liunelson** [DARPA-ASKEM/Model-Representations#18]
We had a discussion on what should shown in the model page of Terarium.
Can we make sure that all the properties^ of "model" have at least: 
1. an unique string that works a short name for this property (expressions would use this)
2. an arbitrarily long string that describes what this property is

^ ("vertices", "edges", "parameters") in RegNets and ("states", "transitions", "parameters") in PetriNets

Currently, (1) is provided inconsistently by "id" and "name while (2) is provided by a "description" that is not always present.

Example:
1. `lotka_volterra.json`: 
> "model": {"vertices": [{"id": "R", description": "Population of rabbits", ...}
2. `sir.json`:
> "model": {"states": [{"id": "S", "description": "Population of susceptible humans", ...}

**Comment by jpfairbanks** [comment]
We probably want all three levels of length? Like `R, Rabbits, The population of rabbits`
