### ISSUE TITLE
Inconsistent JSON formatting

### ISSUE THREAD

**Issue by bgyori** [DARPA-ASKEM/Model-Representations#23]
While working on changing various schemas and examples to introduce semantics, I realized that many of the JSON files don't use standard formatting that e.g., the Python JSON serializer can reproduce.

For instance, here we have a combination of 4 spaces and 2 spaces for indentation here:
```json
{
    "name": "SIR Model",
    "schema": "https://raw.githubusercontent.com/DARPA-ASKEM/Model-Representations/petrinet_v0.1/petrinet/petrinet_schema.json",
    "description": "SIR model created by Ben, Micah, Brandon",
    "model_version": "0.1",
    "model": {
      "states": [
        {
          "id": "S",
          "name": "Susceptible",
          "grounding": {
            "identifiers": {"ido": "0000514"}
          },

```
and a compact format of single-line values for properties:
```json
    "properties": {
      "name": {"type": "string"},
      "schema": {"type": "string", "format": "uri"},
      "description": {"type": "string"},
      "model_version": {"type": "string"},
      "properties": {"type": "object"},
```

I am wondering if I should do a one-time style standardization PR so that later diffs aren't subject to e.g., spurious indentation changes?

**Comment by Nithos** [comment]
I would second that, I am all for automating this. Even using the simple EditorConfig as a baseline without complicating it too much and most IDE's support it.

**Comment by olynch** [comment]
I second this too. Could we also get CI with a style check?

**Comment by bgyori** [comment]
@Nithos and @olynch I did this in a PR with an EditorConfig and added it to CI. If someone can review and approve the PR, we can merge it.
