### ISSUE TITLE
Distribution Names

### ISSUE THREAD

**Issue by jpfairbanks** [DARPA-ASKEM/Model-Representations#48]
I just noticed that in the sir.json example the parameter distribution include this block

```json
: {
            "type": "StandardUniform1",
            "parameters": {
              "minimum": 2.6e-7,
              "maximum": 2.8e-7
            }
          }
```
isn't the standard uniform distribution between [0,1]? Shouldn't this be `Uniform`?

**Comment by bgyori** [comment]
Yes you're right, I realized this too but forgot to update some examples
models. I'll go through and make fixes today.
