### ISSUE TITLE
Create full example of proposed updated decapodes AMR based off of Luke's Grigoriev ice cap example

### ISSUE THREAD

**Issue by mattprintz** [DARPA-ASKEM/Model-Representations#69]
https://algebraicjulia.github.io/Decapodes.jl/dev/grigoriev/

**Comment by liunelson** [comment]
> @liunelson can we use this issue to track creating the TA3 test harness scenarios for climate?

Definitely. I'll also regularly surface the integration dashboard in the TA3 WG meetings to increase its visibility, as with TA1.
